#### House Prices Dataset
#### link: https://www.kaggle.com/c/house-prices-prediction-advanced-regression-techniques/data

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'data.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
print(df.shape)

(1460, 81)

## Feature Engineering

- It is the process of using domain knowledge(numpy, pandas, database, data viz.) to select, transform and create new features from raw data -> make machine learning models accurate and effective

In [4]:
# Drop irrelevant columns

df.drop(columns=['Id'],errors='ignore', inplace=True)

In [5]:
df.head(1)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500

## Handling Missing Values

In [6]:
#Check missing values count
missingvalues = df.isnull().sum()
missingvalues = missingvalues[missingvalues > 0].sort_values(ascending=False)
print(missingvalues)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
MasVnrArea         8
Electrical         1
dtype: int64

In [7]:
# Percentage of TRUE in Total Values
missing_percentage = df.isnull().mean().sort_values(ascending=False)
print(missing_percentage)

PoolQC         0.995205
MiscFeature    0.963014
Alley          0.937671
Fence          0.807534
MasVnrType     0.597260
                 ...
Heating        0.000000
HeatingQC      0.000000
MSZoning       0.000000
1stFlrSF       0.000000
SalePrice      0.000000
Length: 80, dtype: float64

In [8]:
# Drop columns with too many missing values
threshold = 0.65
columns_with_high_null_values = missing_percentage[missing_percentage > threshold].index.tolist()
print(columns_with_high_null_values)

['PoolQC', 'MiscFeature', 'Alley', 'Fence']

In [9]:
df_1 = df.drop(columns=columns_with_high_null_values, errors='ignore')

In [10]:
df_1.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [11]:
df_1.shape

(1460, 76)

In [12]:
import numpy as np

In [21]:
target_correlation = df_1.select_dtypes(include=[np.number]).corr()
print(target_correlation)

               MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  \
MSSubClass       1.000000    -0.386347 -0.139781     0.032628    -0.059316
LotFrontage     -0.386347     1.000000  0.426095     0.251646    -0.059213
LotArea         -0.139781     0.426095  1.000000     0.105806    -0.005636
OverallQual      0.032628     0.251646  0.105806     1.000000    -0.091932
OverallCond     -0.059316    -0.059213 -0.005636    -0.091932     1.000000
YearBuilt        0.027850     0.123349  0.014228     0.572323    -0.375983
YearRemodAdd     0.040581     0.088866  0.013788     0.550684     0.073741
MasVnrArea       0.022936     0.193458  0.104160     0.411876    -0.128101
BsmtFinSF1      -0.069836     0.233633  0.214103     0.239666    -0.046231
BsmtFinSF2      -0.065649     0.049900  0.111170    -0.059119     0.040229
BsmtUnfSF       -0.140759     0.132644 -0.002618     0.308159    -0.136841
TotalBsmtSF     -0.238518     0.392075  0.260833     0.537808    -0.171098
1stFlrSF        -0.251758     0.457181  0.299475     0.476224    -0.144203
2ndFlrSF         0.307886     0.080177  0.050986     0.295493     0.028942
LowQualFinSF     0.046474     0.038469  0.004779    -0.030429     0.025494
GrLivArea        0.074853     0.402797  0.263116     0.593007    -0.079686
BsmtFullBath     0.003491     0.100949  0.158155     0.111098    -0.054942
BsmtHalfBath    -0.002333    -0.007234  0.048046    -0.040150     0.117821
FullBath         0.131608     0.198769  0.126031     0.550600    -0.194149
HalfBath         0.177354     0.053532  0.014259     0.273458    -0.060769
BedroomAbvGr    -0.023438     0.263170  0.119690     0.101676     0.012980
KitchenAbvGr     0.281721    -0.006069 -0.017784    -0.183882    -0.087001
TotRmsAbvGrd     0.040380     0.352096  0.190015     0.427452    -0.057583
Fireplaces      -0.045569     0.266639  0.271364     0.396765    -0.023820
GarageYrBlt      0.085072     0.070250 -0.024947     0.547766    -0.324297
GarageCars      -0.040110     0.285691  0.154871     0.600671    -0.185758
GarageArea      -0.098672     0.344997  0.180403     0.562022    -0.151521
WoodDeckSF      -0.012579     0.088521  0.171698     0.238923    -0.003334
OpenPorchSF     -0.006100     0.151972  0.084774     0.308819    -0.032589
EnclosedPorch   -0.012037     0.010700 -0.018340    -0.113937     0.070356
3SsnPorch       -0.043825     0.070029  0.020423     0.030371     0.025504
ScreenPorch     -0.026030     0.041383  0.043160     0.064886     0.054811
PoolArea         0.008283     0.206167  0.077672     0.065166    -0.001985
MiscVal         -0.007683     0.003368  0.038068    -0.031406     0.068777
MoSold          -0.013585     0.011200  0.001205     0.070815    -0.003511
YrSold          -0.021407     0.007450 -0.014261    -0.027347     0.043950
SalePrice       -0.084284     0.351799  0.263843     0.790982    -0.077856

               YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  \
MSSubClass      0.027850      0.040581    0.022936   -0.069836   -0.065649
LotFrontage     0.123349      0.088866    0.193458    0.233633    0.049900
LotArea         0.014228      0.013788    0.104160    0.214103    0.111170
OverallQual     0.572323      0.550684    0.411876    0.239666   -0.059119
OverallCond    -0.375983      0.073741   -0.128101   -0.046231    0.040229
YearBuilt       1.000000      0.592855    0.315707    0.249503   -0.049107
YearRemodAdd    0.592855      1.000000    0.179618    0.128451   -0.067759
MasVnrArea      0.315707      0.179618    1.000000    0.264736   -0.072319
BsmtFinSF1      0.249503      0.128451    0.264736    1.000000   -0.050117
BsmtFinSF2     -0.049107     -0.067759   -0.072319   -0.050117    1.000000
BsmtUnfSF       0.149040      0.181133    0.114442   -0.495251   -0.209294
TotalBsmtSF     0.391452      0.291066    0.363936    0.522396    0.104810
1stFlrSF        0.281986      0.240379    0.344501    0.445863    0.097117
2ndFlrSF        0.010308      0.140024    0.174561   -0.137079   -0.099260
LowQualFinSF   -0.183784     -0.062419   -0.069071   -0.064503    0.014807
GrLivArea       0.199010      0.287389    0.390857    0.208171   -0.009640
BsmtFullBath    0.187599      0.119470    0.085310    0.649212    0.158678
BsmtHalfBath   -0.038162     -0.012337    0.026673    0.067418    0.070948
FullBath        0.468271      0.439046    0.276833    0.058543   -0.076444
HalfBath        0.242656      0.183331    0.201444    0.004262   -0.032148
BedroomAbvGr   -0.070651     -0.040581    0.102821   -0.107355   -0.015728
KitchenAbvGr   -0.174800     -0.149598   -0.037610   -0.081007   -0.040751
TotRmsAbvGrd    0.095589      0.191740    0.280682    0.044316   -0.035227
Fireplaces      0.147716      0.112581    0.249070    0.260011    0.046921
GarageYrBlt     0.825667      0.642277    0.252691    0.153484   -0.088011
GarageCars      0.537850      0.420622    0.364204    0.224054   -0.038264
GarageArea      0.478954      0.371600    0.373066    0.296970   -0.018227
WoodDeckSF      0.224880      0.205726    0.159718    0.204306    0.067898
OpenPorchSF     0.188686      0.226298    0.125703    0.111761    0.003093
EnclosedPorch  -0.387268     -0.193919   -0.110204   -0.102303    0.036543
3SsnPorch       0.031355      0.045286    0.018796    0.026451   -0.029993
ScreenPorch    -0.050364     -0.038740    0.061466    0.062021    0.088871
PoolArea        0.004950      0.005829    0.011723    0.140491    0.041709
MiscVal        -0.034383     -0.010286   -0.029815    0.003571    0.004940
MoSold          0.012398      0.021490   -0.005965   -0.015727   -0.015211
YrSold         -0.013618      0.035743   -0.008201    0.014359    0.031706
SalePrice       0.522897      0.507101    0.477493    0.386420   -0.011378

               ...  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
MSSubClass     ...   -0.012579    -0.006100      -0.012037  -0.043825
LotFrontage    ...    0.088521     0.151972       0.010700   0.070029
LotArea        ...    0.171698     0.084774      -0.018340   0.020423
OverallQual    ...    0.238923     0.308819      -0.113937   0.030371
OverallCond    ...   -0.003334    -0.032589       0.070356   0.025504
YearBuilt      ...    0.224880     0.188686      -0.387268   0.031355
YearRemodAdd   ...    0.205726     0.226298      -0.193919   0.045286
MasVnrArea     ...    0.159718     0.125703      -0.110204   0.018796
BsmtFinSF1     ...    0.204306     0.111761      -0.102303   0.026451
BsmtFinSF2     ...    0.067898     0.003093       0.036543  -0.029993
BsmtUnfSF      ...   -0.005316     0.129005      -0.002538   0.020764
TotalBsmtSF    ...    0.232019     0.247264      -0.095478   0.037384
1stFlrSF       ...    0.235459     0.211671      -0.065292   0.056104
2ndFlrSF       ...    0.092165     0.208026       0.061989  -0.024358
LowQualFinSF   ...   -0.025444     0.018251       0.061081  -0.004296
GrLivArea      ...    0.247433     0.330224       0.009113   0.020643
BsmtFullBath   ...    0.175315     0.067341      -0.049911  -0.000106
BsmtHalfBath   ...    0.040161    -0.025324      -0.008555   0.035114
FullBath       ...    0.187703     0.259977      -0.115093   0.035353
HalfBath       ...    0.108080     0.199740      -0.095317  -0.004972
BedroomAbvGr   ...    0.046854     0.093810       0.041570  -0.024478
KitchenAbvGr   ...   -0.090130    -0.070091       0.037312  -0.024600
TotRmsAbvGrd   ...    0.165984     0.234192       0.004151  -0.006683
Fireplaces     ...    0.200019     0.169405      -0.024822   0.011257
GarageYrBlt    ...    0.224577     0.228425      -0.297003   0.023544
GarageCars     ...    0.226342     0.213569      -0.151434   0.035765
GarageArea     ...    0.224666     0.241435      -0.121777   0.035087
WoodDeckSF     ...    1.000000     0.058661      -0.125989  -0.032771
OpenPorchSF    ...    0.058661     1.000000      -0.093079  -0.005842
EnclosedPorch  ...   -0.125989    -0.093079       1.000000  -0.037305
3SsnPorch      ...   -0.032771    -0.005842      -0.037305   1.000000
ScreenPorch    ...   -0.074181     0.074304      -0.082864  -0.031436
PoolArea       ...    0.073378     0.060762       0.054203  -0.007992
MiscVal        ...   -0.009551    -0.018584       0.018361   0.000354
MoSold         ...    0.021011     0.071255      -0.028887   0.029474
YrSold         ...    0.022270    -0.057619      -0.009916   0.018645
SalePrice      ...    0.324413     0.315856      -0.128578   0.044584

               ScreenPorch  PoolArea   MiscVal    MoSold    YrSold  SalePrice
MSSubClass       -0.026030  0.008283 -0.007683 -0.013585 -0.021407  -0.084284
LotFrontage       0.041383  0.206167  0.003368  0.011200  0.007450   0.351799
LotArea           0.043160  0.077672  0.038068  0.001205 -0.014261   0.263843
OverallQual       0.064886  0.065166 -0.031406  0.070815 -0.027347   0.790982
OverallCond       0.054811 -0.001985  0.068777 -0.003511  0.043950  -0.077856
YearBuilt        -0.050364  0.004950 -0.034383  0.012398 -0.013618   0.522897
YearRemodAdd     -0.038740  0.005829 -0.010286  0.021490  0.035743   0.507101
MasVnrArea        0.061466  0.011723 -0.029815 -0.005965 -0.008201   0.477493
BsmtFinSF1        0.062021  0.140491  0.003571 -0.015727  0.014359   0.386420
BsmtFinSF2        0.088871  0.041709  0.004940 -0.015211  0.031706  -0.011378
BsmtUnfSF        -0.012579 -0.035092 -0.023837  0.034888 -0.041258   0.214479
TotalBsmtSF       0.084489  0.126053 -0.018479  0.013196 -0.014969   0.613581
1stFlrSF          0.088758  0.131525 -0.021096  0.031372 -0.013604   0.605852
2ndFlrSF          0.040606  0.081487  0.016197  0.035164 -0.028700   0.319334
LowQualFinSF      0.026799  0.062157 -0.003793 -0.022174 -0.028921  -0.025606
GrLivArea         0.101510  0.170205 -0.002416  0.050240 -0.036526   0.708624
BsmtFullBath      0.023148  0.067616 -0.023047 -0.025361  0.067049   0.227122
BsmtHalfBath      0.032121  0.020025 -0.007367  0.032873 -0.046524  -0.016844
FullBath         -0.008106  0.049604 -0.014290  0.055872 -0.019669   0.560664
HalfBath          0.072426  0.022381  0.001290 -0.009050 -0.010269   0.284108
BedroomAbvGr      0.044300  0.070703  0.007767  0.046544 -0.036014   0.168213
KitchenAbvGr     -0.051613 -0.014525  0.062341  0.026589  0.031687  -0.135907
TotRmsAbvGrd      0.059383  0.083757  0.024763  0.036907 -0.034516   0.533723
Fireplaces        0.184530  0.095074  0.001409  0.046357 -0.024096   0.466929
GarageYrBlt      -0.075418 -0.014501 -0.032417  0.005337 -0.001014   0.486362
GarageCars        0.050494  0.020934 -0.043080  0.040522 -0.039117   0.640409
GarageArea        0.051412  0.061047 -0.027400  0.027974 -0.027378   0.623431
WoodDeckSF       -0.074181  0.073378 -0.009551  0.021011  0.022270   0.324413
OpenPorchSF       0.074304  0.060762 -0.018584  0.071255 -0.057619   0.315856
EnclosedPorch    -0.082864  0.054203  0.018361 -0.028887 -0.009916  -0.128578
3SsnPorch        -0.031436 -0.007992  0.000354  0.029474  0.018645   0.044584
ScreenPorch       1.000000  0.051307  0.031946  0.023217  0.010694   0.111447
PoolArea          0.051307  1.000000  0.029669 -0.033737 -0.059689   0.092404
MiscVal           0.031946  0.029669  1.000000 -0.006495  0.004906  -0.021190
MoSold            0.023217 -0.033737 -0.006495  1.000000 -0.145721   0.046432
YrSold            0.010694 -0.059689  0.004906 -0.145721  1.000000  -0.028923
SalePrice         0.111447  0.092404 -0.021190  0.046432 -0.028923   1.000000

[37 rows x 37 columns]

In [14]:
# Filter by Importance
# (Correlation with salePrice)

target_correlation = df_1.select_dtypes(include=[np.number]).corr()['SalePrice'].abs()
low_impact_threshold = 0.1    # any feature with correlation less than this will be considered low impact
low_impact_features = target_correlation[target_correlation < low_impact_threshold].index.tolist()
print(low_impact_features)

['MSSubClass', 'OverallCond', 'BsmtFinSF2', 'LowQualFinSF', 'BsmtHalfBath', '3SsnPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

In [15]:
df_2 = df_1.drop(columns=low_impact_features, errors='ignore')

In [16]:
df_2.shape

(1460, 66)

In [17]:
# Removing multi-collinearity
correlation_matrix = df_2.select_dtypes(include=[np.number]).corr().abs()
upper_triangle = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))
redundant_features = [column for column in upper_triangle.columns if any(upper_triangle[column] > 0.8)]
print(redundant_features)

['1stFlrSF', 'TotRmsAbvGrd', 'GarageYrBlt', 'GarageArea']